---
ID: "7d155704-d9c4-4fbf-835d-bbfb26cabf79"
Parent: "893ac76f-121a-470c-9f4e-9ec24a567d56"
Template: "893ac76f-121a-470c-9f4e-9ec24a567d56"
Path: /sitecore/templates/Project/CoreSite/Page Types/Base/Base Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181017T134705Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
